apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostgo-app
  labels:
    web: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      web: app-service
  template:
    spec:
      containers:
        - name: hostgo-container
          image: registry.csail.app/hostgo
          ports:
            - containerPort: 4005
              protocol: TCP
              name: access-port
          env:
            - name: K8S_CONFIG_DIR
              value: /var/kube/config
            - name: MINIO_ACCESS_KEY
              value: yourMinioKey
            - name: MINIO_SECRET_KEY
              value: yourMinioSecret
            - name: MINIO_HOST
              value: storage-service:9000
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            - name: JWT_SECRET
              value: jwt$ecre7
            - name: PROXY_SECRET
              value: s3cret
            - name: SERVER_URL
              value: csail.app
          imagePullPolicy: Always
      imagePullSecrets:
        - name: hostgo-secret
      volumes:
        - name: dind-storage
          emptyDir: {}
    metadata:
      labels:
        web: app-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-service
  template:
    spec:
      containers:
        - name: proxy-container
          image: registry.csail.app/proxy
          ports:
            - containerPort: 9093
              protocol: TCP
              name: proxy-port
            - containerPort: 80
              protocol: TCP
              name: acc-httpport
            - containerPort: 443
              protocol: TCP
              name: https-port
          env:
            - name: REDIS_HOST
              value: proxy-redis-service:6379
            - name: PROXY_SECRET
              value: s3cret
      imagePullSecrets:
        - name: hostgo-secret
    metadata:
      labels:
        app: proxy-service