apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: proxy-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "registry.app.csail"
      http:
        paths:
          - backend:
              serviceName: registry-service
              servicePort: 6003
    - host: "app.csail"
      http:
        paths:
          - backend:
              serviceName: echo-service
              servicePort: 5678
    - host: "kubernetes.docker.internal"
      http:
        paths:
          - backend:
              serviceName: echo-service
              servicePort: 5678
  backend:
    serviceName: echo-service
    servicePort: 5678