apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app: db-config
data:
  POSTGRES_DB: hostgolang
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: manman

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: object-store-config
  labels:
    app: storage-service
data:
  MINIO_ACCESS_KEY: yourMinioKey
  MINIO_SECRET_KEY: yourMinioSecret

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-config
  labels:
    app: k8s-config
data:
  K8S_CONFIG_B64: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhv
    cml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VSS2Vr
    TkRRV2NyWjBGM1NVSkJaMGxEUW01VmQwUlJXVXBMYjFwSmFIWmpUa0ZSUlV4Q1VVRjNUWHBGVmsx
    Q1RVZEJNVlZGUTJoTlRWSkhiRzRLWVZoU2FHSkZPV3BhVjBaMVRWSnZkMGRCV1VSV1VWRkVSWGhH
    Y2s5SVRtaFpXRTFuVVRKNE1XTXpVbXhqYVVKRVVWUkJaVVozTUhsTlJFRjRUVlJqZUFwTlZGRjZU
    V3BLWVVaM01EQk5SRUY0VFZSamVFMVVVWHBOYWtwaFRVUk5lRVpVUVZSQ1owNVdRa0Z2VkVSRlVu
    QmFNbXd3V1ZkNFVGa3lWbWhpYWtWaENrMUNaMGRCTVZWRlFYaE5VbUY2YUhwWlYwWjZTVVZPYzJS
    WVRqQmFXRWxuVVRCRmQyZG5SV2xOUVRCSFExTnhSMU5KWWpORVVVVkNRVkZWUVVFMFNVSUtSSGRC
    ZDJkblJVdEJiMGxDUVZGRGEyZE1ZVTV2U1ZwR01YWlFTak5IT1ZkQk5UbHBTQ3RDUmtjd2FFNVNh
    bTV4ZUdwT0wzTmtXV055Wm1aTmQwUmxUQXBXYjNOdGVIaHFURlp4VURKRFYzWlVNbkJIUlZwUVYx
    VXZObE51WVU1T09EYzFSbmd3VkRSMVoyazJkRVk0Vm5WcWVIVTNZa2czTDJ0SlRVeG9jVk5YQ21W
    dWRUaGtaRmRxVXpNMGJYQmxVVU0zVlZaV1pHWlJha1ZDVVZkQllXNW9VMnA1ZDJjM1NXRnlTelZ5
    YTNsdWJFeDNiMms1Umtnd2RERjZORTlyTURrS1dYbzRVREZZYVU5UU1XTjRSRTg0YURCWFF6TlFR
    bnBTYnpFMFdsaFlTbFpQYWtOcVprMTFhMW94YTJSblZscEdlbU5xWjBWR1RsSkxaR05KYVdaU1dB
    cGpWVUpvYUZrNWNUbHVVMmRaZEdOeFIzcEVTa3c0VFZOQ1RuUjBPVTR5VjFSMVJ6bEVjSEYwUlRO
    b1lVSjZWVFJQZG5ad1NWUnhSa051TkZscGNsWnpDbWMwVlZkWE5WZGtRamhLUTJsS1RtaHJjVGRy
    VmpaaVRTdGFTSGhOYkhKM1pqaDFZa0ZuVFVKQlFVZHFVbFJDUkUxQk5FZEJNVlZrUkhkRlFpOTNV
    VVVLUVhkSlFtaHFRVk5DWjA1V1NGSk5Ra0ZtT0VWRFJFRkhRVkZJTDBGblJVRk5RakJIUVRGVlpF
    Um5VVmRDUWxSUlZrOHlhakpOVlZjdlF6RjRhRGx4Y2dwM1VWaEhaMHhJU1RscVFVNUNaMnR4YUd0
    cFJ6bDNNRUpCVVhOR1FVRlBRMEZSUlVGUFpuTlBSVkJPUmpKVFpVUnljemRSUW1OcVFVbHBZMGRM
    WldveENrWXpPR3BGVW1SQk5rdHRUamd4WW5sVVRUVkVkM1kwU2xaWWFFYzNTM2RNYUVzMmNFcFNa
    SFIxYkRaRlkxTXdWa2RKVmxNM1drcE9kblpZU1ZkSFMxUUtVRWR4ZEhsTk5VMWpXSEI1UlN0T05E
    SnpNMWN6TW1OQmJVTjRkRXB5TW1GS01uVkNTVkJ2YVROa1JVMHhTalZIVjNaUE9UYzRkRkJqVUdK
    TWNVcFNhQXB2UkhrdlRHZzRlVzV4ZDJOUlNXNVFVWFpYYVVSeVVqaFVhSE5aZFZwallrY3hTRmhT
    VG5NeFRIZHFaMUZFZUZSbmRsTXZhRzlQZW1adFZsSktPRUZQQ25SMmQxVm9LM0YyTW14M2RWUlVL
    MFI2VGxGc1YzazJTWGhXVjFKbGIxZE1VRnBpZGxaWVUxRXZNSFo2UlZSTVltTmtTM0ZKVWtOUVEx
    WjFhRmczU1V3S1NuWlJTekZ4Vkd0VGJGQTFaV2xJTTFwdlFqQm5aVU4yU1VGeVVscHhTMDlNWkRs
    T1lWbDJPVTE1ZURWVVdERkllVkZETUN0bFZqZzRkejA5Q2kwdExTMHRSVTVFSUVORlVsUkpSa2xE
    UVZSRkxTMHRMUzBLCiAgICBzZXJ2ZXI6IGh0dHBzOi8vODI1ZjliNTktOGMyMS00ZjZhLTk5MGYt
    MzIwNmY5YTdiMjg2Lms4cy5vbmRpZ2l0YWxvY2Vhbi5jb20KICBuYW1lOiBkby1ueWMxLWhvc3Rn
    by1kZXYtY2x1c3Rlcgpjb250ZXh0czoKLSBjb250ZXh0OgogICAgY2x1c3RlcjogZG8tbnljMS1o
    b3N0Z28tZGV2LWNsdXN0ZXIKICAgIHVzZXI6IGRvLW55YzEtaG9zdGdvLWRldi1jbHVzdGVyLWFk
    bWluCiAgbmFtZTogZG8tbnljMS1ob3N0Z28tZGV2LWNsdXN0ZXIKY3VycmVudC1jb250ZXh0OiBk
    by1ueWMxLWhvc3Rnby1kZXYtY2x1c3RlcgpraW5kOiBDb25maWcKcHJlZmVyZW5jZXM6IHt9CnVz
    ZXJzOgotIG5hbWU6IGRvLW55YzEtaG9zdGdvLWRldi1jbHVzdGVyLWFkbWluCiAgdXNlcjoKICAg
    IGV4ZWM6CiAgICAgIGFwaVZlcnNpb246IGNsaWVudC5hdXRoZW50aWNhdGlvbi5rOHMuaW8vdjFi
    ZXRhMQogICAgICBhcmdzOgogICAgICAtIGt1YmVybmV0ZXMKICAgICAgLSBjbHVzdGVyCiAgICAg
    IC0ga3ViZWNvbmZpZwogICAgICAtIGV4ZWMtY3JlZGVudGlhbAogICAgICAtIC0tdmVyc2lvbj12
    MWJldGExCiAgICAgIC0gLS1jb250ZXh0PWRlZmF1bHQKICAgICAgLSA4MjVmOWI1OS04YzIxLTRm
    NmEtOTkwZi0zMjA2ZjlhN2IyODYKICAgICAgY29tbWFuZDogZG9jdGwKICAgICAgZW52OiBudWxs
    Cg==