apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: proxy-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  rules:
    - host: "*.hostgoapp.com"
      http:
        paths:
          - backend:
              serviceName: proxy-service
              servicePort: 9093
    - host: "api.hostgoapp.com"
      http:
        paths:
          - backend:
              serviceName: app-service
              servicePort: 4005