apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: le-cluster-isr
  namespace: cert-manager
spec:
  acme:
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adigunhammed.lekan@gmail.com
    privateKeySecretRef:
      name: le-certs-key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: do-secret-data
              key: access-token
---
# le = letsencrypt
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: prod-le
  namespace: cert-manager
spec:
  secretName: le-certs-secret
  issuerRef:
    name: le-cluster-isr
    kind: ClusterIssuer
  commonName: hostgoapp.com
  dnsNames:
    - hostgoapp.com
    - '*.hostgoapp.com'