apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: staging-issuer
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: adigunhammed.lekan@gmail.com
    privateKeySecretRef:
      name: staging-private-key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: do-secret-data
              key: access-token
        selector: {}
      - http01:
          ingress:
            class: nginx
          selector: {}
---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: hostgo-staging-certs
  namespace: default
spec:
  secretName: hostgo-dev-secret
  issuerRef:
    name: staging-issuer
    kind: ClusterIssuer
  commonName: hostgoapp.com
  dnsNames:
    - hostgoapp.com
    - '*.hostgoapp.com'