apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adigunhammed.lekan@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cnameStrategy: Follow
          digitalocean:
            tokenSecretRef:
              name: do-secret-data
              key: access-token

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: hostgo-prod-certs
spec:
  secretName: hostgo-prod-certs
  issuerRef:
    name: letsencrypt-prod
  commonName: hostgoapp.com
  dnsNames:
    - hostgoapp.com
    - "*.hostgoapp.com"