apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: issuer-dev
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: adigunhammed.lekan@gmail.com
    privateKeySecretRef:
      name: staging-private-key
    solvers:
      - dns01:
          cnameStrategy: Follow
          digitalocean:
            tokenSecretRef:
              name: do-secret-data
              key: access-token

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: hostgo-staging-certs
  namespace: cert-manager
spec:
  secretName: hostgo-dev-secret
  issuerRef:
    name: issuer-dev
    kind: ClusterIssuer
  commonName: hostgoapp.com
  dnsNames:
    - hostgoapp.com
    - "*.hostgoapp.com"