apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: adigunhammed.lekan@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cnameStrategy: Follow
          digitalocean:
            tokenSecretRef:
              name: do-secret-data
              key: access-token

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: hostgo-certificate
spec:
  secretName: hostgo-certificates
  issuerRef:
    name: letsencrypt-staging
  commonName: hostgoapp.com
  dnsNames:
    - hostgoapp.com
    - "*.hostgoapp.com"