version: "3"

services:
  # MAIN APPLICATION DATABASE
  database:
    image: postgres:latest
    container_name: hostgo-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manman
      POSTGRES_DB: hostgolang
      PGDATA: /var/lib/postgresql/hostgolang/data/db
    volumes:
      - "${HOME}/mnt/hostgolang/data:/var/lib/postgresql/data"
    ports:
      - "59010:5432"

  # REDIS SESSION STORE
  redis:
    image: redis:latest
    ports:
      - 59011:6379
    volumes:
      - "${HOME}/mnt/hostgolang/redis/data:/data"

  # LOCAL DOCKER REGISTRY
  docker-registry:
    restart: always
    image: registry:2
    ports:
      - 5001:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /mnt/registry/auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /mnt/registry/data
    volumes:
      - "${HOME}/mnt/hostgo/registry/data:/mnt/registry/data"
      - "${HOME}/mnt/hostgo/registry/auth/registry.password:/mnt/registry/auth/registry.password"
      - "${HOME}/mnt/hostgo/build:/mnt/build"

  # RELEASE OBJECT STORAGE
  minio:
    image: minio/minio
    container_name: minio_server
    command: server /mnt/data
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioAccessKey
      MINIO_SECRET_KEY: minioSecretKey
    volumes:
      - "${HOME}/mnt/hostgolang/minio/build:/mnt/data"
    ports:
      - "59013:9000"

  # APPLICATION
  app:
    build: ..
    container_name: hostgolang-web
    volumes:
      - "${HOME}/.kube/config:/var/kube/config"
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - database
      - minio
      - redis
      - docker-registry
      - proxy
    restart: on-failure
    environment:
      - K8S_CONFIG_DIR=/var/kube/config
    ports:
      - "4005:4005"

  # PROXY SERVICE DISCOVERY STORAGE
  redis-proxy:
    image: redis:latest
    ports:
      - 59014:6379
    volumes:
      - "${HOME}/mnt/hostgolang/proxy-redis/data:/data"

  # PROXY
  proxy:
    image: registry.hostgolang.com/proxy:latest
    container_name: hostgo-proxy
    volumes:
      - ${HOME}/mnt/certs:/mnt/certs
    restart: on-failure
    depends_on:
      - redis-proxy
    environment:
      - REDIS_HOST=redis-proxy:6379
    ports:
      - "9093:9093"